<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
//        source of countries data: https://gist.github.com/metal3d/5b925077e66194551df949de64e910f6#file-country-coord-csv

        $countries = [
            ['name' => 'Afghanistan', 'latitude' => 33.0, 'longitude' => 65.0],
            ['name' => 'Albania', 'latitude' => 41.0, 'longitude' => 20.0],
            ['name' => 'Algeria', 'latitude' => 28.0, 'longitude' => 3.0],
            ['name' => 'American Samoa', 'latitude' => -14.3333, 'longitude' => -170.0],
            ['name' => 'Andorra', 'latitude' => 42.5, 'longitude' => 1.6],
            ['name' => 'Angola', 'latitude' => -12.5, 'longitude' => 18.5],
            ['name' => 'Anguilla', 'latitude' => 18.25, 'longitude' => -63.1667],
            ['name' => 'Antarctica', 'latitude' => -90.0, 'longitude' => 0.0],
            ['name' => 'Antigua and Barbuda', 'latitude' => 17.05, 'longitude' => -61.8],
            ['name' => 'Argentina', 'latitude' => -34.0, 'longitude' => -64.0],
            ['name' => 'Armenia', 'latitude' => 40.0, 'longitude' => 45.0],
            ['name' => 'Aruba', 'latitude' => 12.5, 'longitude' => -69.9667],
            ['name' => 'Australia', 'latitude' => -27.0, 'longitude' => 133.0],
            ['name' => 'Austria', 'latitude' => 47.3333, 'longitude' => 13.3333],
            ['name' => 'Azerbaijan', 'latitude' => 40.5, 'longitude' => 47.5],
            ['name' => 'Bahamas', 'latitude' => 24.25, 'longitude' => -76.0],
            ['name' => 'Bahrain', 'latitude' => 26.0, 'longitude' => 50.55],
            ['name' => 'Bangladesh', 'latitude' => 24.0, 'longitude' => 90.0],
            ['name' => 'Barbados', 'latitude' => 13.1667, 'longitude' => -59.5333],
            ['name' => 'Belarus', 'latitude' => 53.0, 'longitude' => 28.0],
            ['name' => 'Belgium', 'latitude' => 50.8333, 'longitude' => 4.0],
            ['name' => 'Belize', 'latitude' => 17.25, 'longitude' => -88.75],
            ['name' => 'Benin', 'latitude' => 9.5, 'longitude' => 2.25],
            ['name' => 'Bermuda', 'latitude' => 32.3333, 'longitude' => -64.75],
            ['name' => 'Bhutan', 'latitude' => 27.5, 'longitude' => 90.5],
            ['name' => 'Bolivia', 'latitude' => -17.0, 'longitude' => -65.0],
            ['name' => 'Bosnia and Herzegovina', 'latitude' => 44.0, 'longitude' => 18.0],
            ['name' => 'Botswana', 'latitude' => -22.0, 'longitude' => 24.0],
            ['name' => 'Bouvet Island', 'latitude' => -54.4333, 'longitude' => 3.4],
            ['name' => 'Brazil', 'latitude' => -10.0, 'longitude' => -55.0],
            ['name' => 'British Indian Ocean Territory', 'latitude' => -6.0, 'longitude' => 71.5],
            ['name' => 'Brunei Darussalam', 'latitude' => 4.5, 'longitude' => 114.6667],
            ['name' => 'Bulgaria', 'latitude' => 43.0, 'longitude' => 25.0],
            ['name' => 'Burkina Faso', 'latitude' => 13.0, 'longitude' => -2.0],
            ['name' => 'Burundi', 'latitude' => -3.5, 'longitude' => 30.0],
            ['name' => 'Cambodia', 'latitude' => 13.0, 'longitude' => 105.0],
            ['name' => 'Cameroon', 'latitude' => 6.0, 'longitude' => 12.0],
            ['name' => 'Canada', 'latitude' => 60.0, 'longitude' => -95.0],
            ['name' => 'Cape Verde', 'latitude' => 16.0, 'longitude' => -24.0],
            ['name' => 'Cayman Islands', 'latitude' => 19.5, 'longitude' => -80.5],
            ['name' => 'Central African Republic', 'latitude' => 7.0, 'longitude' => 21.0],
            ['name' => 'Chad', 'latitude' => 15.0, 'longitude' => 19.0],
            ['name' => 'Chile', 'latitude' => -30.0, 'longitude' => -71.0],
            ['name' => 'China', 'latitude' => 35.0, 'longitude' => 105.0],
            ['name' => 'Christmas Island', 'latitude' => -10.5, 'longitude' => 105.6667],
            ['name' => 'Cocos (Keeling) Islands', 'latitude' => -12.5, 'longitude' => 96.8333],
            ['name' => 'Colombia', 'latitude' => 4.0, 'longitude' => -72.0],
            ['name' => 'Comoros', 'latitude' => -12.1667, 'longitude' => 44.25],
            ['name' => 'Congo', 'latitude' => -1.0, 'longitude' => 15.0],
            ['name' => 'Congo, the Democratic Republic of the', 'latitude' => 0.0, 'longitude' => 25.0],
            ['name' => 'Cook Islands', 'latitude' => -21.2333, 'longitude' => -159.7667],
            ['name' => 'Costa Rica', 'latitude' => 10.0, 'longitude' => -84.0],
            ['name' => 'Côte d\'Ivoire', 'latitude' => 8.0, 'longitude' => -5.0],
            ['name' => 'Croatia', 'latitude' => 45.1667, 'longitude' => 15.5],
            ['name' => 'Cuba', 'latitude' => 21.5, 'longitude' => -80.0],
            ['name' => 'Cyprus', 'latitude' => 35.0, 'longitude' => 33.0],
            ['name' => 'Czech Republic', 'latitude' => 49.75, 'longitude' => 15.5],
            ['name' => 'Denmark', 'latitude' => 56.0, 'longitude' => 10.0],
            ['name' => 'Djibouti', 'latitude' => 11.5, 'longitude' => 43.0],
            ['name' => 'Dominica', 'latitude' => 15.4167, 'longitude' => -61.3333],
            ['name' => 'Dominican Republic', 'latitude' => 19.0, 'longitude' => -70.6667],
            ['name' => 'Ecuador', 'latitude' => -2.0, 'longitude' => -77.5],
            ['name' => 'Egypt', 'latitude' => 27.0, 'longitude' => 30.0],
            ['name' => 'El Salvador', 'latitude' => 13.8333, 'longitude' => -88.9167],
            ['name' => 'Equatorial Guinea', 'latitude' => 2.0, 'longitude' => 10.0],
            ['name' => 'Eritrea', 'latitude' => 15.0, 'longitude' => 39.0],
            ['name' => 'Estonia', 'latitude' => 59.0, 'longitude' => 26.0],
            ['name' => 'Ethiopia', 'latitude' => 8.0, 'longitude' => 38.0],
            ['name' => 'Falkland Islands (Malvinas)', 'latitude' => -51.75, 'longitude' => -59.0],
            ['name' => 'Faroe Islands', 'latitude' => 62.0, 'longitude' => -7.0],
            ['name' => 'Fiji', 'latitude' => -18.0, 'longitude' => 175.0],
            ['name' => 'Finland', 'latitude' => 64.0, 'longitude' => 26.0],
            ['name' => 'France', 'latitude' => 46.0, 'longitude' => 2.0],
            ['name' => 'French Guiana', 'latitude' => 4.0, 'longitude' => -53.0],
            ['name' => 'French Polynesia', 'latitude' => -15.0, 'longitude' => -140.0],
            ['name' => 'French Southern Territories', 'latitude' => -43.0, 'longitude' => 67.0],
            ['name' => 'Gabon', 'latitude' => -1.0, 'longitude' => 11.75],
            ['name' => 'Gambia', 'latitude' => 13.4667, 'longitude' => -16.5667],
            ['name' => 'Georgia', 'latitude' => 42.0, 'longitude' => 43.5],
            ['name' => 'Germany', 'latitude' => 51.0, 'longitude' => 9.0],
            ['name' => 'Ghana', 'latitude' => 8.0, 'longitude' => -2.0],
            ['name' => 'Gibraltar', 'latitude' => 36.1833, 'longitude' => -5.3667],
            ['name' => 'Greece', 'latitude' => 39.0, 'longitude' => 22.0],
            ['name' => 'Greenland', 'latitude' => 72.0, 'longitude' => -40.0],
            ['name' => 'Grenada', 'latitude' => 12.1167, 'longitude' => -61.6667],
            ['name' => 'Guadeloupe', 'latitude' => 16.25, 'longitude' => -61.5833],
            ['name' => 'Guam', 'latitude' => 13.4667, 'longitude' => 144.7833],
            ['name' => 'Guatemala', 'latitude' => 15.5, 'longitude' => -90.25],
            ['name' => 'Guernsey', 'latitude' => 49.5, 'longitude' => -2.56],
            ['name' => 'Guinea', 'latitude' => 11.0, 'longitude' => -10.0],
            ['name' => 'Guinea-Bissau', 'latitude' => 12.0, 'longitude' => -15.0],
            ['name' => 'Guyana', 'latitude' => 5.0, 'longitude' => -59.0],
            ['name' => 'Haiti', 'latitude' => 19.0, 'longitude' => -72.4167],
            ['name' => 'Heard Island and McDonald Islands', 'latitude' => -53.1, 'longitude' => 72.5167],
            ['name' => 'Holy See (Vatican City State)', 'latitude' => 41.9, 'longitude' => 12.45],
            ['name' => 'Honduras', 'latitude' => 15.0, 'longitude' => -86.5],
            ['name' => 'Hong Kong', 'latitude' => 22.25, 'longitude' => 114.1667],
            ['name' => 'Hungary', 'latitude' => 47.0, 'longitude' => 20.0],
            ['name' => 'Iceland', 'latitude' => 65.0, 'longitude' => -18.0],
            ['name' => 'India', 'latitude' => 20.0, 'longitude' => 77.0],
            ['name' => 'Indonesia', 'latitude' => -5.0, 'longitude' => 120.0],
            ['name' => 'Iran', 'latitude' => 32.0, 'longitude' => 53.0],
            ['name' => 'Iraq', 'latitude' => 33.0, 'longitude' => 44.0],
            ['name' => 'Ireland', 'latitude' => 53.0, 'longitude' => -8.0],
            ['name' => 'Isle of Man', 'latitude' => 54.23, 'longitude' => -4.55],
            ['name' => 'Israel', 'latitude' => 31.5, 'longitude' => 34.75],
            ['name' => 'Italy', 'latitude' => 42.8333, 'longitude' => 12.8333],
            ['name' => 'Jamaica', 'latitude' => 18.25, 'longitude' => -77.5],
            ['name' => 'Japan', 'latitude' => 36.0, 'longitude' => 138.0],
            ['name' => 'Jersey', 'latitude' => 49.21, 'longitude' => -2.13],
            ['name' => 'Jordan', 'latitude' => 31.0, 'longitude' => 36.0],
            ['name' => 'Kazakhstan', 'latitude' => 48.0, 'longitude' => 68.0],
            ['name' => 'Kenya', 'latitude' => 1.0, 'longitude' => 38.0],
            ['name' => 'Kiribati', 'latitude' => 1.4167, 'longitude' => 173.0],
            ['name' => "Korea, Democratic People's Republic of", 'latitude' => 40.0, 'longitude' => 127.0],
            ['name' => 'Korea, Republic of', 'latitude' => 37.0, 'longitude' => 127.5],
            ['name' => 'Kuwait', 'latitude' => 29.3375, 'longitude' => 47.6581],
            ['name' => 'Kyrgyzstan', 'latitude' => 41.0, 'longitude' => 75.0],
            ['name' => "Lao People's Democratic Republic", 'latitude' => 18.0, 'longitude' => 105.0],
            ['name' => 'Latvia', 'latitude' => 57.0, 'longitude' => 25.0],
            ['name' => 'Lebanon', 'latitude' => 33.8333, 'longitude' => 35.8333],
            ['name' => 'Lesotho', 'latitude' => -29.5, 'longitude' => 28.5],
            ['name' => 'Liberia', 'latitude' => 6.5, 'longitude' => -9.5],
            ['name' => 'Libyan Arab Jamahiriya', 'latitude' => 25.0, 'longitude' => 17.0],
            ['name' => 'Liechtenstein', 'latitude' => 47.1667, 'longitude' => 9.5333],
            ['name' => 'Lithuania', 'latitude' => 56.0, 'longitude' => 24.0],
            ['name' => 'Luxembourg', 'latitude' => 49.75, 'longitude' => 6.1667],
            ['name' => 'Macao', 'latitude' => 22.1667, 'longitude' => 113.55],
            ['name' => 'Macedonia, the Former Yugoslav Republic of', 'latitude' => 41.8333, 'longitude' => 22.0],
            ['name' => 'Madagascar', 'latitude' => -20.0, 'longitude' => 47.0],
            ['name' => 'Malawi', 'latitude' => -13.5, 'longitude' => 34.0],
            ['name' => 'Malaysia', 'latitude' => 2.5, 'longitude' => 112.5],
            ['name' => 'Maldives', 'latitude' => 3.25, 'longitude' => 73.0],
            ['name' => 'Mali', 'latitude' => 17.0, 'longitude' => -4.0],
            ['name' => 'Malta', 'latitude' => 35.8333, 'longitude' => 14.5833],
            ['name' => 'Marshall Islands', 'latitude' => 9.0, 'longitude' => 168.0],
            ['name' => 'Martinique', 'latitude' => 14.6667, 'longitude' => -61.0],
            ['name' => 'Mauritania', 'latitude' => 20.0, 'longitude' => -12.0],
            ['name' => 'Mauritius', 'latitude' => -20.2833, 'longitude' => 57.55],
            ['name' => 'Mayotte', 'latitude' => -12.8333, 'longitude' => 45.1667],
            ['name' => 'Mexico', 'latitude' => 23.0, 'longitude' => -102.0],
            ['name' => 'Micronesia, Federated States of', 'latitude' => 6.9167, 'longitude' => 158.25],
            ['name' => 'Moldova, Republic of', 'latitude' => 47.0, 'longitude' => 29.0],
            ['name' => 'Monaco', 'latitude' => 43.7333, 'longitude' => 7.4],
            ['name' => 'Mongolia', 'latitude' => 46.0, 'longitude' => 105.0],
            ['name' => 'Montenegro', 'latitude' => 42.0, 'longitude' => 19.0],
            ['name' => 'Montserrat', 'latitude' => 16.75, 'longitude' => -62.2],
            ['name' => 'Morocco', 'latitude' => 32.0, 'longitude' => -5.0],
            ['name' => 'Mozambique', 'latitude' => -18.25, 'longitude' => 35.0],
            ['name' => 'Myanmar', 'latitude' => 22.0, 'longitude' => 98.0],
            ['name' => 'Namibia', 'latitude' => -22.0, 'longitude' => 17.0],
            ['name' => 'Nauru', 'latitude' => -0.5333, 'longitude' => 166.9167],
            ['name' => 'Nepal', 'latitude' => 28.0, 'longitude' => 84.0],
            ['name' => 'Netherlands', 'latitude' => 52.5, 'longitude' => 5.75],
            ['name' => 'Netherlands Antilles', 'latitude' => 12.25, 'longitude' => -68.75],
            ['name' => 'New Caledonia', 'latitude' => -21.5, 'longitude' => 165.5],
            ['name' => 'New Zealand', 'latitude' => -41.0, 'longitude' => 174.0],
            ['name' => 'Nicaragua', 'latitude' => 13.0, 'longitude' => -85.0],
            ['name' => 'Niger', 'latitude' => 16.0, 'longitude' => 8.0],
            ['name' => 'Nigeria', 'latitude' => 10.0, 'longitude' => 8.0],
            ['name' => 'Niue', 'latitude' => -19.0333, 'longitude' => -169.8667],
            ['name' => 'Norfolk Island', 'latitude' => -29.0333, 'longitude' => 167.95],
            ['name' => 'Northern Mariana Islands', 'latitude' => 15.2, 'longitude' => 145.75],
            ['name' => 'Norway', 'latitude' => 62.0, 'longitude' => 10.0],
            ['name' => 'Oman', 'latitude' => 21.0, 'longitude' => 57.0],
            ['name' => 'Pakistan', 'latitude' => 30.0, 'longitude' => 70.0],
            ['name' => 'Palau', 'latitude' => 7.5, 'longitude' => 134.5],
            ['name' => 'Palestinian Territory, Occupied', 'latitude' => 32.0, 'longitude' => 35.25],
            ['name' => 'Panama', 'latitude' => 9.0, 'longitude' => -80.0],
            ['name' => 'Papua New Guinea', 'latitude' => -6.0, 'longitude' => 147.0],
            ['name' => 'Paraguay', 'latitude' => -23.0, 'longitude' => -58.0],
            ['name' => 'Peru', 'latitude' => -10.0, 'longitude' => -76.0],
            ['name' => 'Philippines', 'latitude' => 13.0, 'longitude' => 122.0],
            ['name' => 'Pitcairn', 'latitude' => -24.7, 'longitude' => -127.4],
            ['name' => 'Poland', 'latitude' => 52.0, 'longitude' => 20.0],
            ['name' => 'Portugal', 'latitude' => 39.5, 'longitude' => -8.0],
            ['name' => 'Puerto Rico', 'latitude' => 18.25, 'longitude' => -66.5],
            ['name' => 'Qatar', 'latitude' => 25.5, 'longitude' => 51.25],
            ['name' => 'Réunion', 'latitude' => -21.1, 'longitude' => 55.6],
            ['name' => 'Romania', 'latitude' => 46.0, 'longitude' => 25.0],
            ['name' => 'Russian Federation', 'latitude' => 60.0, 'longitude' => 100.0],
            ['name' => 'Rwanda', 'latitude' => -2.0, 'longitude' => 30.0],
            ['name' => 'Saint Helena, Ascension and Tristan da Cunha', 'latitude' => -15.9333, 'longitude' => -5.7],
            ['name' => 'Saint Kitts and Nevis', 'latitude' => 17.3333, 'longitude' => -62.75],
            ['name' => 'Saint Lucia', 'latitude' => 13.8833, 'longitude' => -61.1333],
            ['name' => 'Saint Pierre and Miquelon', 'latitude' => 46.8333, 'longitude' => -56.3333],
            ['name' => 'Saint Vincent and the Grenadines', 'latitude' => 13.25, 'longitude' => -61.2],
            ['name' => 'Samoa', 'latitude' => -13.5833, 'longitude' => -172.3333],
            ['name' => 'San Marino', 'latitude' => 43.7667, 'longitude' => 12.4167],
            ['name' => 'Sao Tome and Principe', 'latitude' => 1.0, 'longitude' => 7.0],
            ['name' => 'Saudi Arabia', 'latitude' => 25.0, 'longitude' => 45.0],
            ['name' => 'Senegal', 'latitude' => 14.0, 'longitude' => -14.0],
            ['name' => 'Serbia', 'latitude' => 44.0, 'longitude' => 21.0],
            ['name' => 'Seychelles', 'latitude' => -4.5833, 'longitude' => 55.6667],
            ['name' => 'Sierra Leone', 'latitude' => 8.5, 'longitude' => -11.5],
            ['name' => 'Singapore', 'latitude' => 1.3667, 'longitude' => 103.8],
            ['name' => 'Slovakia', 'latitude' => 48.6667, 'longitude' => 19.5],
            ['name' => 'Slovenia', 'latitude' => 46.0, 'longitude' => 15.0],
            ['name' => 'Solomon Islands', 'latitude' => -8.0, 'longitude' => 159.0],
            ['name' => 'Somalia', 'latitude' => 10.0, 'longitude' => 49.0],
            ['name' => 'South Africa', 'latitude' => -29.0, 'longitude' => 24.0],
            ['name' => 'South Georgia and the South Sandwich Islands', 'latitude' => -54.5, 'longitude' => -37.0],
            ['name' => 'South Sudan', 'latitude' => 8.0, 'longitude' => 30.0],
            ['name' => 'Spain', 'latitude' => 40.0, 'longitude' => -4.0],
            ['name' => 'Sri Lanka', 'latitude' => 7.0, 'longitude' => 81.0],
            ['name' => 'Sudan', 'latitude' => 15.0, 'longitude' => 30.0],
            ['name' => 'Suriname', 'latitude' => 4.0, 'longitude' => -56.0],
            ['name' => 'Svalbard and Jan Mayen', 'latitude' => 78.0, 'longitude' => 20.0],
            ['name' => 'Swaziland', 'latitude' => -26.5, 'longitude' => 31.5],
            ['name' => 'Sweden', 'latitude' => 62.0, 'longitude' => 15.0],
            ['name' => 'Switzerland', 'latitude' => 47.0, 'longitude' => 8.0],
            ['name' => 'Syrian Arab Republic', 'latitude' => 35.0, 'longitude' => 38.0],
            ['name' => 'Taiwan, Province of China', 'latitude' => 23.5, 'longitude' => 121.0],
            ['name' => 'Tajikistan', 'latitude' => 39.0, 'longitude' => 71.0],
            ['name' => 'Tanzania, United Republic of', 'latitude' => -6.0, 'longitude' => 35.0],
            ['name' => 'Thailand', 'latitude' => 15.0, 'longitude' => 100.0],
            ['name' => 'Timor-Leste', 'latitude' => -8.55, 'longitude' => 125.5167],
            ['name' => 'Togo', 'latitude' => 8.0, 'longitude' => 1.1667],
            ['name' => 'Tokelau', 'latitude' => -9.0, 'longitude' => -172.0],
            ['name' => 'Tonga', 'latitude' => -20.0, 'longitude' => -175.0],
            ['name' => 'Trinidad and Tobago', 'latitude' => 11.0, 'longitude' => -61.0],
            ['name' => 'Tunisia', 'latitude' => 34.0, 'longitude' => 9.0],
            ['name' => 'Turkey', 'latitude' => 39.0, 'longitude' => 35.0],
            ['name' => 'Turkmenistan', 'latitude' => 40.0, 'longitude' => 60.0],
            ['name' => 'Turks and Caicos Islands', 'latitude' => 21.75, 'longitude' => -71.5833],
            ['name' => 'Tuvalu', 'latitude' => -8.0, 'longitude' => 178.0],
            ['name' => 'Uganda', 'latitude' => 1.0, 'longitude' => 32.0],
            ['name' => 'Ukraine', 'latitude' => 49.0, 'longitude' => 32.0],
            ['name' => 'United Arab Emirates', 'latitude' => 24.0, 'longitude' => 54.0],
            ['name' => 'United Kingdom', 'latitude' => 54.0, 'longitude' => -2.0],
            ['name' => 'United States', 'latitude' => 38.0, 'longitude' => -97.0],
            ['name' => 'United States Minor Outlying Islands', 'latitude' => 19.2833, 'longitude' => 166.6],
            ['name' => 'Uruguay', 'latitude' => -33.0, 'longitude' => -56.0],
            ['name' => 'Uzbekistan', 'latitude' => 41.0, 'longitude' => 64.0],
            ['name' => 'Vanuatu', 'latitude' => -16.0, 'longitude' => 167.0],
            ['name' => 'Venezuela, Bolivarian Republic of', 'latitude' => 8.0, 'longitude' => -66.0],
            ['name' => 'Viet Nam', 'latitude' => 16.0, 'longitude' => 106.0],
            ['name' => 'Virgin Islands, British', 'latitude' => 18.5, 'longitude' => -64.5],
            ['name' => 'Virgin Islands, U.S.', 'latitude' => 18.3333, 'longitude' => -64.8333],
            ['name' => 'Wallis and Futuna', 'latitude' => -13.3, 'longitude' => -176.2],
            ['name' => 'Western Sahara', 'latitude' => 24.5, 'longitude' => -13.0],
            ['name' => 'Yemen', 'latitude' => 15.0, 'longitude' => 48.0],
            ['name' => 'Zambia', 'latitude' => -15.0, 'longitude' => 30.0],
            ['name' => 'Zimbabwe', 'latitude' => -20.0, 'longitude' => 30.0],

        ];



        DB::table('countries')->insert($countries);
    }
}
