version: '3.1'
services:
    webserver:
        image: 'nginx:alpine'
        working_dir: /var/www/
        volumes:
            - './:/var/www/'
            - './docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '8080:80'

    php:
        build:
            context: .
            dockerfile: docker/php-fpm/Dockerfile
        working_dir: /var/www/
        volumes:
            - './:/var/www/'

    postgres:
        image: 'postgres:15-alpine'
        volumes:
            - "./pgdata:/var/lib/postgresql/data"
        environment:
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=${DB_DATABASE}
        ports:
            - '5432:5432'
